language: ruby
cache: bundler

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.5

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never
